//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_FinalProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class communeEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public communeEntity()
        {
            this.KhachHangs = new HashSet<KhachHangEntity>();
            this.NhanViens = new HashSet<NhanVienEntity>();
        }
    
        public string commune_id { get; set; }
        public string commune_name { get; set; }
        public Nullable<int> degree { get; set; }
        public string district_id { get; set; }
    
        public virtual districtEntity district { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHangEntity> KhachHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NhanVienEntity> NhanViens { get; set; }
    }
}
