//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_FinalProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class districtEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public districtEntity()
        {
            this.communes = new HashSet<communeEntity>();
        }
    
        public string district_id { get; set; }
        public string district_name { get; set; }
        public string province_id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<communeEntity> communes { get; set; }
        public virtual provinceEntity province { get; set; }
    }
}
