//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_FinalProject.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HotelDBMF : DbContext
    {
        public HotelDBMF()
            : base("name=HotelDBMF")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<communeEntity> communeEntities { get; set; }
        public virtual DbSet<DichVuEntity> DichVuEntities { get; set; }
        public virtual DbSet<districtEntity> districtEntities { get; set; }
        public virtual DbSet<KhachHangEntity> KhachHangEntities { get; set; }
        public virtual DbSet<LoaiPhongEntity> LoaiPhongEntities { get; set; }
        public virtual DbSet<NhanVienEntity> NhanVienEntities { get; set; }
        public virtual DbSet<PhongEntity> PhongEntities { get; set; }
        public virtual DbSet<provinceEntity> provinceEntities { get; set; }
        public virtual DbSet<SuDungDichVuEntity> SuDungDichVuEntities { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<ThanhToanEntity> ThanhToanEntities { get; set; }
        public virtual DbSet<ThuePhongEntity> ThuePhongEntities { get; set; }
    }
}
