//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_FinalProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhongEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PhongEntity()
        {
            this.ThuePhongs = new HashSet<ThuePhongEntity>();
        }
    
        public string MaPhong { get; set; }
        public string MaLoai { get; set; }
        public Nullable<bool> TrangThai { get; set; }
        public string GhiChu { get; set; }
        public string DienTich { get; set; }
        public Nullable<double> GiaThue { get; set; }
        public Nullable<int> SoGiuong { get; set; }
    
        public virtual LoaiPhongEntity LoaiPhong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThuePhongEntity> ThuePhongs { get; set; }
    }
}
