//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_FinalProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuDungDichVuEntity
    {
        public string MaPhong { get; set; }
        public string MaDV { get; set; }
        public string MaThuePhong { get; set; }
        public Nullable<System.DateTime> NgaySuDung { get; set; }
        public Nullable<int> SoLuong { get; set; }
    
        public virtual DichVuEntity DichVu { get; set; }
        public virtual ThuePhongEntity ThuePhong { get; set; }
    }
}
