//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom15_FinalProject.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuePhongEntity
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThuePhongEntity()
        {
            this.SuDungDichVus = new HashSet<SuDungDichVuEntity>();
            this.ThanhToans = new HashSet<ThanhToanEntity>();
        }
    
        public string MaThuePhong { get; set; }
        public string MaPhong { get; set; }
        public string MaNV { get; set; }
        public string CMND { get; set; }
        public string NgayVao { get; set; }
        public string DatCoc { get; set; }
    
        public virtual KhachHangEntity KhachHang { get; set; }
        public virtual NhanVienEntity NhanVien { get; set; }
        public virtual PhongEntity Phong { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SuDungDichVuEntity> SuDungDichVus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThanhToanEntity> ThanhToans { get; set; }
    }
}
